[package]
name = "afx-song-file-toolkit"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
binrw = "0.10.0"
aes = "0.8.2"
cfb-mode = "0.8.2"
hex-literal = "0.3"
