name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_LOG: debug
  RUST_BACKTRACE: 1

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Clippy
        run: rustup component add clippy && cargo clippy
      - name: Build
        run: cargo build
