name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-crate1:
    name: cargo test realtime-audio-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo run --bin realtime-audio-rs
  test-crate2:
    name: cargo test afx-song-file-toolkit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo run --bin afx-song-file-toolkit
